"""Tests for LaunchLint PDF and HTML report generation."""

from __future__ import annotations

from pathlib import Path

from launchlint.core import AuditResult, Issue, Severity
from launchlint.reports import calculate_score, default_report_filename, generate_html, generate_pdf
from launchlint.reports.brand import BrandConfig


def _sample_result() -> AuditResult:
    return AuditResult(
        target="https://example.com",
        checks_run=["seo", "a11y"],
        issues=[
            Issue("seo", Severity.ERROR, "Missing title", location="<title>"),
            Issue("a11y", Severity.WARN, "No lang attribute", suggestion="Add lang=\"en\"."),
            Issue("seo", Severity.INFO, "Missing OG tags"),
        ],
        duration_ms=123,
        meta={"final_url": "https://example.com/", "content_type": "text/html", "size_bytes": 1024},
    )


def test_calculate_score():
    result = _sample_result()
    # 100 - 1*15 - 1*5 - 1*1 = 79
    assert calculate_score(result) == 79


def test_calculate_score_min_zero():
    result = AuditResult(
        target="https://example.com",
        checks_run=["seo"],
        issues=[Issue("seo", Severity.ERROR, "x") for _ in range(10)],
    )
    assert calculate_score(result) == 0


def test_default_report_filename():
    result = _sample_result()
    name = default_report_filename(result, ext="pdf")
    assert name.startswith("launchlint-example.com-")
    assert name.endswith(".pdf")


def test_default_report_filename_local_path():
    result = AuditResult(target="./dist/index.html", checks_run=["seo"])
    name = default_report_filename(result, ext="html")
    assert "index" in name
    assert name.endswith(".html")


def test_generate_pdf(tmp_path: Path):
    result = _sample_result()
    brand = BrandConfig(agency_name="Test Agency", client_name="Test Client")
    output = tmp_path / "report.pdf"
    path = generate_pdf(result, brand, output)
    assert path.exists()
    assert path.stat().st_size > 0


def test_generate_pdf_with_custom_accent(tmp_path: Path):
    result = _sample_result()
    brand = BrandConfig(accent_color="#10B981")
    output = tmp_path / "report.pdf"
    assert generate_pdf(result, brand, output).exists()


def test_generate_pdf_letter(tmp_path: Path):
    result = _sample_result()
    brand = BrandConfig(page_size="Letter")
    output = tmp_path / "report.pdf"
    assert generate_pdf(result, brand, output).exists()


def test_generate_html(tmp_path: Path):
    result = _sample_result()
    brand = BrandConfig(agency_name="HTML Agency")
    output = tmp_path / "report.html"
    path = generate_html(result, brand, output)
    assert path.exists()
    content = path.read_text(encoding="utf-8")
    assert "HTML Agency" in content
    assert "Missing title" in content
    assert "79" in content or "/100" in content


def test_generate_html_no_findings(tmp_path: Path):
    result = AuditResult(target="https://example.com", checks_run=["seo"])
    output = tmp_path / "clean.html"
    path = generate_html(result, BrandConfig(), output)
    content = path.read_text(encoding="utf-8")
    assert "No findings" in content or "Clean launch" in content


def test_generate_html_hide_branding(tmp_path: Path):
    result = _sample_result()
    brand = BrandConfig(hide_branding=True)
    output = tmp_path / "white-label.html"
    path = generate_html(result, brand, output)
    content = path.read_text(encoding="utf-8")
    assert "Generated by LaunchLint" not in content
    assert "<footer>" not in content